// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings to camera_mvp.
class CameraBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  CameraBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  CameraBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int nativeAttach(
    ffi.Pointer<ffi.Void> env,
    ffi.Pointer<ffi.Void> surface,
    int width,
    int height,
  ) {
    return _nativeAttach(env, surface, width, height);
  }

  late final _nativeAttachPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('nativeAttach');
  late final _nativeAttach = _nativeAttachPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, int, int)
      >();

  void nativeDetach(int engineHandle) {
    return _nativeDetach(engineHandle);
  }

  late final _nativeDetachPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>(
        'nativeDetach',
      );
  late final _nativeDetach = _nativeDetachPtr.asFunction<void Function(int)>();

  double getEngineFps(int engineHandle) {
    return _getEngineFps(engineHandle);
  }

  late final _getEngineFpsPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.LongLong)>>(
        'getEngineFps',
      );
  late final _getEngineFps = _getEngineFpsPtr
      .asFunction<double Function(int)>();
}
