[project]
name = "img2img"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "aiohttp>=3.11.8",
    "alembic>=1.18.5",
    "av>=16.0.0",
    "blake3>=1.0.9",
    "comfy-aimdo==0.4.10",
    "comfy-angle>=0.1.0",
    "comfy-kitchen==0.2.22",
    "comfyui-embedded-docs==0.5.8",
    "comfyui-frontend-package==1.47.10",
    "comfyui-workflow-templates==0.11.17",
    "einops>=0.8.2",
    "filelock>=3.32.0",
    "kornia>=0.7.1",
    "mediapipe>=0.10.35",
    "numba>=0.59.0",
    "insightface>=0.7.3",
    "face-alignment>=1.4.1",
    "onnx2torch>=1.5.15",
    "onnxruntime-gpu>=1.27.0",
    "opencv-python>=4.8.0,<4.11.0",
    "pillow>=12.3.0",
    "psutil>=7.2.2",
    "pydantic~=2.0",
    "pydantic-settings~=2.0",
    "pykalman>=0.11.2",
    "pyopengl>=3.1.8",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "safetensors>=0.4.2",
    "sentencepiece>=0.2.2",
    "simpleeval>=1.0.0",
    "spandrel>=0.4.2",
    "sqlalchemy>=2.0.0",
    "tokenizers>=0.13.3",
    "torch>=2.13.0",
    "torchaudio>=2.11.0",
    "torchsde>=0.2.6",
    "torchvision>=0.28.0",
    "tqdm>=4.69.1",
    "transformers>=4.50.3",
    "yarl>=1.18.0",
    "numpy<2.0.0",
    "scipy<1.14.0",
    "protobuf<5.0.0dev",
    "mediapipe==0.10.21",
    "pip",
    "gguf>=0.13.0",
    "ultralytics>=8.3.162",
    "segment-anything",
    "piexif",
    "scikit-image",
    "scikit-learn",
    "dill",
    "matplotlib",
    "imageio",
    "joblib",
    "pilgram",
    "rembg",
    "timm",
    "gitpython",
    "pygithub",
    "matrix-nio",
    "typer",
    "rich",
    "toml",
    "chardet",
]

[tool.uv]
environments = ["sys_platform == 'linux'"]
no-build = true
override-dependencies = [
    "numpy<2.0.0",
    "scipy<1.14.0",
    "protobuf<5.0.0dev",
    "mediapipe==0.10.21",
    "onnxruntime-gpu==1.27.0",
]
